### ISSUE TITLE
Plugin issues with launcher icon in flutter app

### ISSUE THREAD

**Issue by gm4321** [bilalilyas90/paymob_flutter_lib#4]
hi 

i am facing the issue when i change my app launcher icon in flutter app then android default logo shows instead of flutter default logo or my logo that i provides. please help me i am worried about issue.

Best Regards
Ghulam Mustafa

**Comment by bilalilyas90** [comment]
Hi @gm4321 
You can update to latest version i.e 1.0.7 and it will solve your problem.

**Comment by gm4321** [comment]
Hi Bilal,

Thank you soo Much for Great attention for us. Thanks & Regards
